---
# tasks file for cobalt_strike role

# Setup/install task
- include_tasks: "setup-cobaltstrike.yml"
  
- name: Include Cobalt Strike role specific variables
  include_vars: "{{ cobalt_strike_role }}.yml"

- name: Include tasks for Cobalt Strike role Teamserver or Operator
  include_tasks: "configure-{{ cobalt_strike_role }}.yml"

# Cleanup
- name: Delete Cobalt Strike tarballs
  file:
    path: "/tmp/*.tgz"
    state: absent
