---
# tasks file for ad-client
- name: install windows feature AD-DS on DCs
  win_dns_client:
    adapter_names: "*"
    ipv4_addresses:
    - "{{ dc_ip }}"

- name: join domain
  win_domain_membership:
    dns_domain_name: "{{ domain_name }}"
    domain_admin_user: "{{ domain_user }}"
    domain_admin_password: "{{ domain_pw }}"
    state: domain
  register: domain_joined

