---
# playbook for hack-vm

## Task list

# disable account expiry
# disable uac
# disable av and smartscreen
# set dark theme
# set region to norway and time zone
# set network interface to private
# enable smb
# configure shares
# windows updates
# install choco and packages
# set ip and dns for host-only interface
# change hostname
# reboot

- hosts: hack_vm
  tasks:
    - name: disable password expiry
      win_user:
        name: administrator
        password_never_expires: yes
        state: present

    - name: disable uac (reg)
      win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\System
        name: EnableLUA
        data: 0
        type: dword
        state: present

    - name: create registry path for real-time protection
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection
        
    - name: disable defender real time monitoring
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection
        name: DisableRealtimeMonitoring
        data: 1
        type: dword
        state: present

    - name: create registry path for spynet
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows Defender\Spynet

    - name: disable "cloud-delivered protection"
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows Defender\Spynet
        name: SpynetReporting
        data: 0
        type: dword
        state: present

    - name: disable "automatic sample submission"
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows Defender\Spynet
        name: SubmitSamplesConsent
        data: 2
        type: dword
        state: present

    - name: disable defender smartscreen
      win_regedit:
        path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Explorer
        name: SmartScreenEnabled
        data: Off
        type: String
        state: present

    - name: disable light time (enable dark theme)
      win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize
        name: AppsUseLightTheme
        data: 0
        type: dword
        state: present

    - name: set region to norway
      win_shell: |
        Set-WinUserLanguageList -LanguageList nb-NO -force
        Set-WinHomeLocation -geoid 0xb1
        Set-Culture -CultureInfo nb-NO
        Set-TimeZone -Name 'Central Europe Standard Time'

    - name: Enable file sharing
      win_firewall_rule:
        name: "File And Printer Sharing"
        enabled: yes
        state: present

    - name: Add Desktop share
      win_share:
        name: Desktop
        description: Desktop share
        path: C:\Users\Administrator\Desktop
        list: yes
        full: Administrator

    - name: Add Dropbox folder
      win_file:
        path: C:\Users\Administrator\Dropbox
        state: directory

    - name: Add Dropbox share
      win_share:
        name: Dropbox
        description: Dropbox share
        path: C:\Users\Administrator\Dropbox
        list: yes
        full: Administrator

    - name: install all security, critical, and rollup updates without a scheduled task
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        state: installed

    - name: install multiple packages with choco sequentially (avoid rate limiting)
      win_chocolatey:
        name: '{{ item }}'
        state: present
      loop:
      - firefox
      - sublimetext3
      - dropbox
      - google-backup-and-sync
      - 7zip.install
      - git.install
      - nmap
      - vscode.install
      - vscode-powershell
      - vscode-ansible
      - visualstudio2017community
      - jre8
      - microsoft-windows-terminal
      - neo4j-community
      - PSWindowsUpdate
      - procexp
      - wsl
      - wsl-ubuntu-1804
      - vmware-tools

    - name: change hostname
      win_hostname:
        name: "{{ hostname }}"
      register: change_hostname

    - name: reboot if hostname changed
      win_reboot:
      when: change_hostname.reboot_required