---
# playbook for cloning and provisioning VMs in vCenter
# first clone a VM. will always run

- name: clone vm
  import_playbook: vcenter_clone_playbook.yml

# - name: Wait 300 seconds, but only start checking after 60 seconds
#   wait_for_connection:
#     delay: 60
#     timeout: 300
#   when: "'windows' in os"

# runs the playbook specified by template name
- name: configure linux vm
  import_playbook: linux_playbook.yml
  when: "'windows' not in os"

- name: configure windows vm
  import_playbook: w10_playbook.yml
  when: "'windows' in os"