---
# playbook for cloning and provisioning VMs in vCenter

# first clone a VM. will always run
- name: clone vm
  import_playbook: vcenter_clone_playbook.yml

# runs the playbook specified by template name
- name: configure linux vm
  import_playbook: linux_playbook.yml
  when:
  - '"kali" in template_name or "ubuntu" in template_name'

- name: configure windows vm
  import_playbook: w10_playbook.yml
  when: '"w10" in template_name'