---
# playbook for cloning vcenter vm
- hosts: vcenter
  gather_facts: no

  vars_prompt:
    #- name: username
    #  prompt: "Enter your username"
    #  private: no

    - name: password
      prompt: "Enter your password (input hidden)"
      private: yes

    - name: vm_name
      prompt: "Enter your vm name. (will be prefixed with your username)"
      private: no

  tasks:
    - name: Clone a virtual machine from another
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ username }}@{{ domain_name }}"
        password: "{{ password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        folder: "{{ folder_prefix }}/{{ username }}"
        name: "{{ username }}-{{ vm_name }}"
        state: poweredon
        template: "{{ template_name }}"
        disk:
        - size_gb: 60
          type: thin
          datastore: "{{ datastore_name }}"
        hardware:
          memory_mb: 4096
          num_cpus: 2
          num_cpu_cores_per_socket: 1
          scsi: paravirtual
          max_connections: 1
          version: 14 # Hardware version of virtual machine
          boot_firmware: "efi"
        networks:
        - name: "{{ network_name }}"
        wait_for_ip_address: yes
      delegate_to: localhost
      register: vm

    - name: IP address info from VM
      debug:
        msg: "{{ vm.instance.ipv4 }}"

    - name: register host in inventory with ip address
      add_host:
        name: "{{ vm.instance.ipv4 }}"
        groups: new_vm