---
# playbook for cloning vcenter vm
- hosts: vcenter
  gather_facts: no

  vars_prompt:
    #- name: username
    #  prompt: "Enter your username"
    #  private: no

    # - name: password
    #   prompt: "Enter your password (input hidden)"
    #   private: yes

    # - name: vm_name
    #   prompt: "Enter your vm name."
    #   private: no

  tasks:
    - name: Clone a virtual machine from another
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ username }}@{{ domain_name }}"
        password: "{{ password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        folder: "{{ folder_path }}"
        name: "{{ vm_name }}"
        state: poweredon
        template: "{{ template_name }}"
        disk:
        - size_gb: 60
          type: thin
          datastore: "{{ datastore_name }}"
        hardware:
          memory_mb: 4096
          num_cpus: 2
          num_cpu_cores_per_socket: 1
          scsi: paravirtual
          max_connections: 1
          version: 14 # Hardware version of virtual machine
          boot_firmware: "efi"
        networks:
        - name: "{{ network_name }}"
        wait_for_ip_address: yes
      delegate_to: localhost
      register: vm

    - name: IP address info from VM
      debug:
        msg: 'IP: "{{ vm.instance.ipv4 }}"'

    - name: register kali linux host group in dynamic inventory with ip address
      add_host:
        name: "{{ vm.instance.ipv4 }}"
        groups: linux_vm
        ansible_user: kali
      when: '"kali" in template_name'
    
    - name: register ubuntu linux host group in dynamic inventory with ip address
      add_host:
        name: "{{ vm.instance.ipv4 }}"
        groups: linux_vm
        ansible_user: ubuntu
      when: '"ubuntu" in template_name'

    - name: register windows host group in dynamic inventory with ip address
      add_host:
        name: "{{ vm.instance.ipv4 }}"
        groups: windows_vm
      when: '"w10" in template_name'