---
# playbook for cloning and provisioning VMs in vCenter

# first clone a VM. will always run
- name: clone vm
  import_playbook: vcenter_clone_playbook.yml
  tags: 
  - always

# runs the playbook specified by tag. these never run unless explicitly stated
- name: configure windows vm
  import_playbook: w10_playbook.yml
  tags: [never, w10]

- name: configure kali vm
  import_playbook: kali_playbook.yml
  tags: [never, kali]