---
# playbook for windows hacking vm
- hosts: win_hack_vm
  tasks:
    - debug:
      msg: "Always runs"
    - name: include disable_defender role
      include_role:
        name: disable_defender
        
    - name: disable password expiry
      win_user:
        name: administrator
        password_never_expires: yes
        state: present

    - name: disable uac (reg)
      win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\System
        name: EnableLUA
        data: 0
        type: dword
        state: present

    - name: disable light time (enable dark theme)
      win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize
        name: AppsUseLightTheme
        data: 0
        type: dword
        state: present

    - name: Set format, location and unicode to Norway
      win_region:
        location: 177 # norway code
        format: nb-NO
        unicode_language: nb-NO
      register: changed_location

    - name: change time zone to norway
      win_timezone:
        timezone: 'Central Europe Standard Time'
    
    - name: change keyboard to norwegian
      win_shell:
        Set-WinUserLanguageList -LanguageList nb-NO -force

    - name: Enable file sharing
      win_firewall_rule:
        name: "File And Printer Sharing"
        enabled: yes
        state: present

    - name: Add Desktop share
      win_share:
        name: Desktop
        description: Desktop share
        path: C:\Users\Administrator\Desktop
        list: yes
        full: Administrator

    - name: Add Dropbox folder
      win_file:
        path: C:\Users\Administrator\Dropbox
        state: directory

    - name: Add Dropbox share
      win_share:
        name: Dropbox
        description: Dropbox share
        path: C:\Users\Administrator\Dropbox
        list: yes
        full: Administrator

    - name: install all security, critical, and rollup updates without a scheduled task
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        state: installed
      tags:
        - update

    - name: install multiple packages with choco
      win_chocolatey:
        name:
        - firefox
        - sublimetext3
        - dropbox
        - google-backup-and-sync
        - 7zip.install
        - git.install
        - nmap
        - vscode.install
        - vscode-powershell
        - vscode-ansible
        - visualstudio2019community
        - visualstudio2019-workload-manageddesktop
        - azure-cli
        - azurepowershell
        - powershell-core
        - awscli
        - gcloudsdk
        - jre8
        - microsoft-windows-terminal
        - neo4j-community
        - PSWindowsUpdate
        - procexp
        - wsl
        - vmware-tools
        ignore_checksums: yes
        state: latest
      tags:
        - update
      
    - name: change hostname
      win_hostname:
        name: "{{ hostname }}"
      register: changed_hostname

    - name: reboot if hostname or location changed
      win_reboot:
      when: changed_hostname.reboot_required or changed_location.restart_required

    - name: install wsl ubuntu package with choco (only after wsl is enabled and rebooted)
      win_chocolatey:
        name:
        - wsl-ubuntu-1804
        state: latest

    - name: remove OneDrive from Explorer Name Space Tree (64bit)
      win_regedit:
        path: HKCU:\Software\Classes\CLSID\{018D5C66-4533-4307-9B53-224DE2ED1FE6}
        name: System.IsPinnedToNameSpaceTree
        data: 0
        type: dword

    - name: delete lnk files on desktop
      win_shell:
        Remove-Item -Path 'C:\Users\*\Desktop\*.lnk'

    - name: reboot one final time to make sure everything applies
      win_reboot:
      tags: reboot
