---
# tasks file for ad_dc
- name: install windows feature AD-DS on DCs
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present
  register: adds_install

- name: reboot if AD DS was installed
  win_reboot:
  when: adds_install.changed == true

- name: set DNS settings to localhost
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses: "127.0.0.1"

- name: import AD DS PS module
  win_psmodule:
    name: ADDSDeployment
    state: present

- name: configure as Domain Controller
  win_shell:   Install-ADDSForest -DomainName "{{ domain_name }}" -SafeModeAdministratorPassword (ConvertTo-SecureString "{{ safe_pw }}" -AsPlainText -Force) -InstallDns:$true  -NoRebootOnCompletion:$true -Confirm:$false
  register: dc_install

- name: reboot if DC was installed
  win_reboot:
  when: dc_install.changed == true