---
# tasks file for ad_client
- name: configure DNS to DC IP address
  win_dns_client:
    adapter_names: "*"
    ipv4_addresses:
    - "{{ dc_ip }}"

- name: join domain
  win_domain_membership:
    dns_domain_name: "{{ dns_domain_name }}"
    domain_admin_user: "{{ domain_admin_user }}"
    domain_admin_password: "{{ domain_admin_password }}"
    state: domain
  register: domain_joined

- name: reboot if domain joined
  win_reboot:
  when: domain_joined.reboot_required