tasks:
  - name: Update repo and upgrade all packages to the latest version (Debian family)
    apt:
      name: '*'
      update_cache: yes
      state: latest
    tags: update
    when: ansible_os_family == 'Debian'

  - name: Update repo and upgrade all packages to the latest version (Redhat family)
    apt:
      name: '*'
      update_cache: yes
      state: latest
    tags: update
    when: ansible_os_family == 'RedHat'

  - name: Reboot if necessary
    stat:
      path: /var/run/reboot-required
    register: result
    changed_when: result.stat.exists
    notify: 'reboot server'

  # - name: Verify new update
  #   command: uname -mrs
  #   register: uname_result
    
  # - name: Display new kernel version
  #   debug:
  #       var: uname_result.stdout_lines

handlers:
  - name: Reboot server
    shell: 'sleep 5 && shutdown -r now "Rebooting to complete system upgrade"'
    async: 1
    poll: 0
    listen: 'reboot server'

  - name: Wait for host to become available again
    wait_for_connection:
      delay: 30
      connect_timeout: 10
      sleep: 10
      timeout: 300
    listen: 'reboot server'