---
# tasks file for ad_computer

- name: stop windows update service and set to disabled
  win_service:
    name: wuauserv
    start_mode: disabled
    state: stopped
    # force_dependent_services: true

- name: change windows hostname
  win_hostname:
    name: "{{ hostname }}"
  register: change_hostname

- name: reboot if hostname was changed
  win_reboot:
  when: change_hostname.changed == true